defaults:
  - defaults
  - _self_

model: flux-dev
model_path: black-forest-labs/FLUX.1-dev
train_data_path: frank-chieng/chinese_architecture_siheyuan
train_batch_size: 10
num_iterations: 100
resolution: 512
